name: 'Build Windows GTK4'
description: 'Builds Windows GTK4 for obs-deps with specified architecture and build config'
inputs:
  target:
    description: 'Build target for GTK4'
    required: true
  config:
    description: 'Build configuration'
    required: false
    default: 'Release'
  cacheRevision:
    description: 'Cache revision number to force creation of new cache generation'
    required: false
    default: '01'
runs:
  using: 'composite'
  steps:
    - name: Environment Setup
      id: gtk4-env-setup
      shell: pwsh
      run: |
        Get-Content .\deps.gtk4\*.ps1 > temp.txt
        $Gtk4DepHash = ((Get-FileHash -Path temp.txt -Algorithm SHA256).Hash)
        Write-Output "::set-output name=depHash::${Gtk4DepHash}"

    - name: Set up the PATH environment
      shell: bash
      run: |
        echo "C:\pkg-config-lite-0.28-1\bin" >> $GITHUB_PATH

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install pkgconfig-lite
      shell: pwsh
      run: |
        Invoke-WebRequest -Uri https://deac-fra.dl.sourceforge.net/project/pkgconfiglite/0.28-1/pkg-config-lite-0.28-1_bin-win32.zip -OutFile /pkg_config_lite.zip -MaximumRetryCount 5
        Expand-Archive /pkg_config_lite.zip -DestinationPath C:\
        ls C:\
        ls C:\pkg-config-lite-0.28-1
        ls C:\pkg-config-lite-0.28-1\bin
        pkg-config --version

    - name: Install dependencies
      shell: bash
      run: |
        pip install meson ninja
        choco install winflexbison3 -y --force

    - name: Setup MSVC
      uses: bus1/cabuild/action/msdevshell@v1
      with:
        architecture: ${{ inputs.target }}

    - name: Restore Windows GTK4 from Cache
      id: deps-cache
      uses: actions/cache@v3
      with:
        path: |
          ${{ github.workspace }}/*_build_temp/*
          !${{ github.workspace }}/*_build_temp/**/.git
          !${{ github.workspace }}/*_build_temp/*.tar.gz
          !${{ github.workspace }}/*_build_temp/*.tar.xz
          !${{ github.workspace }}/*_build_temp/*.zip
        key: ${{ inputs.target }}-windows-gtk4-${{ inputs.config }}-${{ steps.gtk4-env-setup.outputs.depHash }}-${{ inputs.cacheRevision }}
        restore-keys: ${{ inputs.target }}-windows-gtk4-${{inputs.config }}-${{ steps.gtk4-env-setup.outputs.depHash }}-${{ inputs.cacheRevision }}-

    - name: Install Windows GTK4
      if: ${{ steps.deps-cache.outputs.cache-hit == 'true' }}
      shell: pwsh
      run: ./Build-Dependencies.ps1 -Dependencies "Gtk4" -SkipBuild -SkipUnpack -Target ${{ inputs.target }} -Configuration ${{ inputs.config }} -Shared

    - name: Build and Install Windows GTK4
      if: ${{ steps.deps-cache.outputs.cache-hit != 'true' }}
      shell: pwsh
      run: ./Build-Dependencies.ps1 -Dependencies "Gtk4" -Target ${{ inputs.target }} -Configuration ${{ inputs.config }} -Shared
